//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceType.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User Id=mimic01;Password=mimic01mm1;Data Source=(DESCRIPTION =    (ADDRESS_LIST =" +
            "      (ADDRESS = (PROTOCOL = TCP)(HOST = 10.175.88.100)(PORT = 1521))    )    (C" +
            "ONNECT_DATA =      (SERVICE_NAME = MIMIC1)    )  )")]
        public string oracleconnectionstring {
            get {
                return ((string)(this["oracleconnectionstring"]));
            }
            set {
                this["oracleconnectionstring"] = value;
            }
        }
    }
}
